resource_group_name         = "terraform_course_vm_rg"
resource_group_location     = "West US 2"
virtual_network_name        = "tft-course-vm-vnet"
subnet_name                 = "tft-course-vm-subnet"
public_ip_name              = "tft-course-vm-pub-ip"
network_security_group_name = "tft-course-vm-nsg"
network_interface_name      = "tft-course-vm-nic"
linux_virtual_machine_name  = "tft-course-vm"