resource_group_name    = "terraform_course_kv_rbac_rg"
location               = "West US 2"
keyvault_name          = "tfcoursekeyvltrbac"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"