resource_group_name    = "terraform-course-kv-pwd-rg"
location               = "West US 2"
keyvault_name          = "terraformcoursekv"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"