resource_group_name     = "terraform-course-web-sql-db-rg"
resource_group_location = "West US 2"
app_service_plan_name   = "terraform-course-websqldb-appserviceplan"
app_service_name        = "terraform-course-websqldb-app"
sql_server_name         = "terraform-course-websqldb-sqlserver"
sql_database_name       = "TerraformCoursewebsqlDB"
sql_admin_login         = "user01"
sql_admin_password      = "@Aa123456789!"
